### ISSUE TITLE
ImportError: No module named GraphMLParser

### ISSUE THREAD

**Issue by alexmas0n** [hadim/pygraphml#12]
from pygraphml.GraphMLParser import *
ImportError: No module named GraphMLParser
root@kali:~# import pygraphml
import.im6: unable to open image `pygraphml': Is a directory @ error/blob.c/OpenBlob/2638.
root@kali:~#

**Comment by hadim** [comment]
How did you install pygraphml ? If you've installed it with `pip install`, you have to know that this version is deprecated. You should install it with:

```bash
git clone https://github.com/hadim/pygraphml.git
cd pygraphml/
pip install .
```

I am waiting an admin from pypi repository to remove the old version (uploaded by someone else) so I can upload the new version and `pip install` will works again hopefully !

See this ticket : https://sourceforge.net/p/pypi/support-requests/445/

**Comment by alexmas0n** [comment]
Installed through git clone, says install successful

**Comment by hadim** [comment]
You need to launch a python console to be able to import pygraphml.
Try this `python -c " import pygraphml"`

**Comment by alexmas0n** [comment]
root@kali:~# python -c "import pygraphml"
root@kali:~# 

nothing happens, nothing launches

**Comment by hadim** [comment]
It means that pygraphml has been correctly installed and works well. You
can start writing code using pygraphml! Enjoy :-)

**Comment by alexmas0n** [comment]
Ok. Problem must be with fbstalker.

**Comment by hadim** [comment]
Sorry but it does not look related to pygraphml... I close here.

**Comment by hadim** [comment]
Try this -> `from pygraphml import GraphMLParser`

**Comment by alexmas0n** [comment]
good idea, heres what it says

root@kali:~# from pygraphml import GraphMLParser
from: can't read /var/mail/pygraphml

**Comment by hadim** [comment]
I think there is a misunderstanding about how to use python. You can't use python in a shell. For example you cannot do that: `root@kali:~# print("I am not in python")`. 

You first need to launch a python console

```
root@kali:~# python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print("I am in python")
I am in python
>>> 
```

You can also put some python code in a file and then execute the whole file with Python. For example: 

```
root@kali:~# echo 'print("I am in Python")' > test.py
root@kali:~# cat test.py 
print("I am in Python")
root@kali:~# python test.py 
I am in Python 
```

So this issue is really not related to pygraphml. You should read some python book and learn a bit more about how it works.
